class _BotCommands:
    def __init__(self):
        self.StartCommand = 'startfl'
        self.MirrorCommand = 'mirrorfl'
        self.UnzipMirrorCommand = 'unzipmirrorfl'
        self.TarMirrorCommand = 'tarmirrorfl'
        self.CancelMirror = 'cancelfl'
        self.CancelAllCommand = 'cancelallfl'
        self.ListCommand = 'listfl'
        self.StatusCommand = 'statusfl'
        self.AuthorizedUsersCommand = 'usersfl'
        self.AuthorizeCommand = 'authorizefl'
        self.UnAuthorizeCommand = 'unauthorizefl'
        self.AddSudoCommand = 'addsudofl'
        self.RmSudoCommand = 'rmsudofl'
        self.PingCommand = 'pingfl'
        self.RestartCommand = 'restartfl'
        self.StatsCommand = 'statsfl'
        self.HelpCommand = 'helpfl'
        self.LogCommand = 'logfl'
        self.SpeedCommand = 'speedtestfl'
        self.CloneCommand = 'clonefl'
        self.CountCommand = 'countfl'
        self.WatchCommand = 'watchfl'
        self.TarWatchCommand = 'tarwatchfl'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usagefl'

BotCommands = _BotCommands()
